### ISSUE TITLE
livereload

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/bankai#1]
Hooks are already in place in html, should probably add to sheetify hooks to send a msg when updated

**Comment by bcomnes** [comment]
Whats involved in getting this in?

**Comment by yoshuawuyts** [comment]
Hmm, goooood questiooooon. I believe we're already injecting the script into the `html` so what we'd need to do then is trigger the script each time CSS is updated. Something like that hmm

The fancier stuff would then be to also add hot reloading but that's just an extra plugin on top of this hmm

**Comment by bcomnes** [comment]
I didn't see the live reload script last night when I tried the example. (https://github.com/yoshuawuyts/bankai/pull/69 for some minor changes to that).

 I could be trippin

**Comment by yoshuawuyts** [comment]
Oh odd, seems it was removed in the latest patch. Ah well, could easily be restored C: https://github.com/yoshuawuyts/bankai/blob/0077f522b5d3ba0a1060c725c833f098e3749fbc/handler-html.js#L1

**Comment by marionebl** [comment]
Actually the livereload script was never included. Is this worthwile given hmr could be implemented instead?

**Comment by yoshuawuyts** [comment]
yeah guess we could add hmr for `css` at low cost too so that seems like the better way to go for sure

**Comment by bcomnes** [comment]
I would rather see live reload if it means seeing it sooner than an HMR solution.  I've not had great experiences with HMR in the past.  It requires that you modify code to work with it right?

**Comment by yoshuawuyts** [comment]
@bcomnes nah in this case we would go for the naive option - save the state object globally; reload the `<script>` tag with the new script and reattach the state. Using SSE / WS it should be fairly straight forward. But as you say it could indeed lead to edge cases when modifying `models` so yeahhh. Overall I think it's useful in some cases for sure

**Comment by timwis** [comment]
What about people who want to use bankai for projects that don't have global state the same way choo/redux style apps do? Just browserify built apps. They'd probably need live reload.

**Comment by marionebl** [comment]
Boils down to: What is this? A beefy/budo clone or something more specialized? 

My view of bankai 

* tailored to "idiomatic" choo 
* batteries (hmr, css-in-js, index html, build) included
* zero config
* use budo if you need more flexibility

**Comment by yoshuawuyts** [comment]
I think you're both right. The way I view `bankai` is probably somewhere in the middle:
- library to hook into a streaming HTTP server to serve frontend bundles
- CLI with sensible defaults for developing single state application (e.g. `choo`)
- CLI with sensible defaults for creating production ready static files
- flexible enough to be used with other frontend frameworks by toggling flags

Does that make sense?

**Comment by yoshuawuyts** [comment]
closing in favor of #31
