### ISSUE TITLE
breaks when insert-css usage isn't naively statically analyzable

### ISSUE THREAD

**Issue by ahdinosaur** [yoshuawuyts/bankai#109]
hey, so this has come up for me a few times, most recently when i used [`ngraph.pixel/lib/tooltip.js#L12`](https://github.com/anvaka/ngraph.pixel/blob/master/lib/tooltip.js#L12).

basically, if any code uses `insert-css` in a way that isn't naively statically analyzable (if it uses a variable defined elsewhere, even if it's not dynamic), `bankai` removes the `insertCss = require('insert-css')` but leaves the expression using `insertCss` that it couldn't analyze.

leaving this issue here because it happens when i use `bankai`, even though i'm guessing it's [`css-extract`](https://github.com/stackcss/css-extract)'s fault.

**Comment by yoshuawuyts** [comment]
I reckon the most straight forward fix would be to detect if code is
statically analyzable or not, and leave statements in place if it isn't.
How do you propose we handle that?

**Comment by ahdinosaur** [comment]
yeah i agree. i'll try to get a failing test to isolate the problem, it might be a bug with [`static-module`](https://github.com/substack/static-module).

**Comment by ahdinosaur** [comment]
hey, got something working: https://github.com/stackcss/css-extract/pull/12. :full_moon_with_face:  seems a bit hacky for some reason, but works.

**Comment by yoshuawuyts** [comment]
No updates in almost half a year, gonna assume it's been resolved. Let me know if there's still any issues regarding this. Thanks!
