### ISSUE TITLE
optimize: true breaks es6 compatibility

### ISSUE THREAD

**Issue by MattMcFarland** [yoshuawuyts/bankai#117]
**Steps to reproduce:**

1. Create a blank project using bankai

2. For your client.js code, simply add the following lines:

```javascript

var foo = `bar`
var func = (args) => console.log
```

**Expected results**
Should be no error

**Actual results**
the node instance blows up and appears that `uglifyjs` is parsing with es5 rules.

**some notes/findings:**
**Using babelify, es2020 do not work**

When trying to use those as transforms in `package.json` or passed into browserify using the `js` property you get another error stating that the `path to client.js cannot be found`. If you disable `yoyoify` you then get the same damn uglifyjs error anyway.  I think that the transforms might not be called in the correct order, but I am not sure.  

**yoyoify transpiles backticks if you use them with bel/yo/choo**  - Optimize will not fail if you are using template tag strings that are passed in to bel/yo/choo - but that is the only case.  using fat arrow functions though will not work at all.

**Suggested fix**
Let developers overload `js` or `optimize` and have the ability to explicitly use different transforms when `optimize` is true.  this could be messy but this would add some flexibility.

Or maybe ditch the uglifyjs transform all together and just pipe the finished browserify stream to uglifyjs when everything is done?? idk if that will work but right now I'm just not sure how to get this to work other than to use es5 only which makes me sad.

See also: https://github.com/mishoo/UglifyJS2/issues/1411

**Comment by MattMcFarland** [comment]
I am happy to send PR but I dont know what strategy we should take for fixing this.. thoughts are welcome :)

**Comment by yoshuawuyts** [comment]
so which of these lines is failng? What happens if you disable one of them?

**Comment by MattMcFarland** [comment]
Both fail

**Comment by MattMcFarland** [comment]
I think one way to fix this would be to transpile before it is sent to uglifyjs.  However, if you transpile first then call yoyoify it blows up.

The problem is that yoyoify has to be called before you transpile and you have to transpile before you run uglifyjs - I havent confirmed this but that is the only thing that makes logical sense to me atm.

**Comment by yoshuawuyts** [comment]
Yeah I think what you're saying makes sense. I think you can circumvent
this by including es2020 + yo-yoify in your package JSON though, in the
right order

**Comment by rahatarmanahmed** [comment]
The workaround for this, as @yoshuawuyts says, is to have duplicate yoyoify and sheetify transforms before babelify. Not ideal but it seems to work.

```js
const jsOpts = {
  js: {
    transform: [
      'envify',
      'sheetify/transform',
      'yo-yoify',
      ['babelify', { presets: ['latest'] }]
    ]
  },
  optimize: true
}
const clientPath = path.join(__dirname, '../client/app.js')
client = bankai(clientPath, jsOpts)
```

**Comment by delvedor** [comment]
Hi guys, same problem here!
Solved in this way:
```json
"script": {
"build:browser": "bankai build browser/index.js --optimize --electron build-browser/"
}
"browserify": {
  "transform": [
    "unassertify",
    "yo-yoify",
    "es2020"
  ]
}
```

**Comment by yoshuawuyts** [comment]
You can now do `--uglify false` and it should no longer crash, can just pull in your own uglify (: Given the lack of activity I think this issue has been resolved. Feel free to reopen if it hasn't been. Cheers!
