### ISSUE TITLE
README to be fixed

### ISSUE THREAD

**Issue by nicocube** [yoshuawuyts/bankai#132]
Hi all,

First of I would say that I am really fond of your project and I just want to make a contribution to make it better. :)

I found out while integrating bankai in my codebase that in the current README there is a tricky error in the proposed code:
```javascript
var bankai = require('bankai')
var http = require('http')
var path = require('path')

var clientPath = path.join(__dirname, 'client.js')
var assets = bankai(clientPath)

http.createServer((req, res) => {
  switch (req.url) {
    case '/': return assets.html(req, res).pipe(res)
    case '/bundle.js': return assets.js(req, res).pipe(res)
    case '/bundle.css': return assets.css(req, res).pipe(res)
    default: return (res.statusCode = 404 && res.end('404 not found'))
  }
}).listen(8080)
```
In the `default` clause, the `&&` operator has precedence on the `=` operator[[1]], so in fact the value stored in res.statusCode is not `404` but `true`. The fact that res.statusCode store the value `true` make the response come with a `200` status code, which is not the expected behavior.

To make it more explicit, the following line:
```javascript
    default: return (res.statusCode = 404 && res.end('404 not found'))
```
is equivalent with explicit parentheses to
```javascript
    default: return (res.statusCode = (404 && res.end('404 not found')))
```
Which store `true` into `res.statusCode`.

So the line should be fixed with explicit parentheses as such:
```javascript
    default: return (res.statusCode = 404) && res.end('404 not found')
```
Sorry for not making a pull request, but I do think the matter is too small that it would need such.

[1]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

**Comment by yoshuawuyts** [comment]
Thanks heaps for spotting this! - PRs are always welcome tho, no matter how small :sparkles:

Fixed it for now thoo :grin: - I'm glad you're enjoying `bankai` :sparkles:
