### ISSUE TITLE
listen on host different to localhost 

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/bankai#144]
This is a litle feature request, but maybe is an edge case. The thing is that listening on localhost works fine for most cases, but in my case, I'm developing on a cloud ide (c9.io) and I can run almost anything with the litle condition that it must be run on `0.0.0.0:8080` and not `localhost:8080`. So, running `bankai start -p 8080` is crashing.
So, would it be posible to pass an option to bankai cli to configure the host? what would be a good option, since `-h` and `-H` are already taken? Maybe `-a` for `--address`?

**Comment by yoshuawuyts** [comment]
Hmm, yeah I think address sounds reasonable. Imo the c9 people should fix
this in their IDE by aliasing it, but yeah I'd like you to also not be
blocked by this so I'm cool with adding it.

**Comment by YerkoPalma** [comment]
Cool then, bankai api is quite simple so I think I can add this :+1: 
And I agree, the IDE should fix that
