### ISSUE TITLE
include envify

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/bankai#149]
As per https://github.com/yoshuawuyts/choo/issues/444 (woot, triples!) we should probably be running `envify` to do the `process.env.NODE_ENV` stuff for `--optimize`. I think this should be fairly similar to other transforms. Happy to help if someone wants to pick this up!

**Comment by YerkoPalma** [comment]
That would be adding envify to [this block of code](https://github.com/yoshuawuyts/bankai/blob/master/index.js#L82-L87)?

**Comment by yoshuawuyts** [comment]
@YerkoPalma :sparkles: right on
