### ISSUE TITLE
using uglifyify by default breaks arrow functions

### ISSUE THREAD

**Issue by lordvlad** [yoshuawuyts/bankai#157]
taking choo's minimal example and changing the view to read

```javascript
function mainView (state, emit) {
  var onclick = () => emit('increment', 1)

  return html`
    <body>
      <h1>count is ${state.count}</h1>
      <button onclick=${onclick}>Increment</button>
    </body>
  `
}
```

and running `bankai build index ./target` produces an `unexpected token: punc ())` error with bankai 7.0.0, but works fine with bankai 6.1.1.

**Comment by timmak** [comment]
add https://github.com/yoshuawuyts/es2020  to your browserify transforms for the moment, now that you can't opt out of optimize

**Comment by toddself** [comment]
uglify doesn't work with post es5 code.  the example should be updated and the docs should be updated.

**Comment by yoshuawuyts** [comment]
PR welcome!

**Comment by toddself** [comment]
Here is a PR to fix this: https://github.com/yoshuawuyts/bankai/pull/158

**Comment by yoshuawuyts** [comment]
Merged, closing!
