### ISSUE TITLE
[question] Allow disables in build command

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/bankai#192]
Sometimes is cleaner to have a `index.html` file instead of make it through `--html` option. So I was wondering, does it make sense to allow html disable in build command, I was thinking like

```bash
$ bankai build --html=false index.js
```

that would output only `bundle.js` and `bundle.css`. Right now, the API allow to disable html and css, so it sounds logical to me to do the same for the cli. What do you think?

**Comment by yoshuawuyts** [comment]
We could do a thing that if there's an `index.html` in your local directory
it uses that instead - if possible I'd prefer to not have any more options
haha (:

**Comment by YerkoPalma** [comment]
@yoshuawuyts what do you think of doing that for `start` command also? if there is a `index.html` file present, use that instead of the one provided by `create_html` package.

**Comment by yoshuawuyts** [comment]
Yeah, sounds good. PR welcome!
