### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/bankai#43]
having one would be grand

**Comment by marionebl** [comment]
Is this a "help wanted"?

**Comment by yoshuawuyts** [comment]
@marionebl ooh, if you're offering to help - yes please!

**Comment by marionebl** [comment]
I do! I'll shell out a minimal prototype as common ground  for discussion this weekend; a sentence or two about the primary usecase you have in mind would help, though! :rocket:

**Comment by yoshuawuyts** [comment]
Wooh, rad! I updated my previous post with what I had envisioned, let me know how that sounds to you.

Probably worth noting is that `livereload` should probs be its own endpoint so the script can be served :sparkles:

**Comment by marionebl** [comment]
Sounds good to me. To clarify things, I understood the following:

* the cli provides means to start a server (http) or dump artifacts on disk (fs); think `bankai start` vs `bankai build`
* in the fs case, there would be distinct one-off and watch modes
* as a library, `bankai` becomes agnostic to the question if it streams to http or fs or at least learns to cater for both
* `NODE_ENV` enables different default configurations
* cli and programatic interface allow for full customization
* livereload should be added using the same port on a distinct endpoint

I'd begin with the `bankai start` bit, get livereload working and integrate options to allow for the same level of configurability the programatic integration currently allows.

That should sum up to a big-enough PR to get an impression on how to collaborate on this. What do you think?

**Comment by yoshuawuyts** [comment]
Ooh, yeah I like `bankai start` & `bankai build`. Your summary sounds excellent; real excited to see this happen! 🚲

The only suggestion I have is that perhaps in addition to `NODE_ENV` it'd be nice to allow toggling based on a direct flag (e.g. `--optimize` or similar). Not too fussed to get a first pass perfect though, but I like the idea of having all CLI switches be enumerable in the API itself. Heaps thanks again! :grin:

**Comment by yoshuawuyts** [comment]
Ooh, also we could totes turn this into something closer to https://twitter.com/_developit/status/759178282570887168 in the long term hah

**Comment by yoshuawuyts** [comment]
Welp, we got a CLI now :grin:
