### ISSUE TITLE
Cannot use insert-css

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/bankai#49]
This might be an issue with `sheetify` or `css-extract` rather than bankai, but I've noticed that you can't do the following on a bankai server:

```javascript
const insertCSS = require('insert-css')
insertCSS('html, body { height: 100%; }')
```

The page will throw an error that `insertCSS` is not defined. I believe it's because the browserify transform that bankai runs removes all `require('insert-css')` references. It _does_ work if I do it on the same line:
```javascript
require('insert-css')('html, body { height: 100%; }')
```
Which seems to support the theory.

**Comment by yoshuawuyts** [comment]
yeah, we expect `insert-css` to be used in a certain way in [css-extract](https://github.com/stackcss/css-extract). Is this a problem for what you were trying to do?

**Comment by timwis** [comment]
My workaround works, more that the usage instructions in the insert-css readme don't work in this setup and it's unclear why (the error message suggests it's not installed or something).

**Comment by yoshuawuyts** [comment]
Moved to https://github.com/stackcss/css-extract/issues/7 as it's an issue with `extract-css`
