### ISSUE TITLE
add installify

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/bankai#51]
would be cool to be able to put `installify` in the repo and like have auto installs all over the place. Yeah that'd be cool C:
- https://github.com/hughsk/installify

**Comment by yoshuawuyts** [comment]
maybe

**Comment by bcomnes** [comment]
(if you do add it, make it optional?)

**Comment by yoshuawuyts** [comment]
yeah that sounds alright hah (:

**Comment by yoshuawuyts** [comment]
ok nah not gonna do this I think
