### ISSUE TITLE
[feature] serve source maps

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/bankai#53]
Source maps make it much easier to debug. Happy to pitch in on this but wanted to check first in case it was intentionally excluded.

**Comment by yoshuawuyts** [comment]
nope, PR welcome!

**Comment by yoshuawuyts** [comment]
renaming to "serve source maps" - we really ought to use source maps yeah haha :p

**Comment by yoshuawuyts** [comment]
yeah ok so this works now for JS - external source maps aren't a thing, but feel using `exorcist` is very much possible sooo yeah just gonna leave it for now (: - labelling this as "good enough"
