### ISSUE TITLE
Change --optimize to another word

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/bankai#54]
I'd like to suggest changing the `--optimize` flag to another word so that we can use `-o` for the output path in the build tool just like `browserify` offers. Perhaps `--production`?

**Comment by yoshuawuyts** [comment]
haha, but then `--production` would conflict with `--port`. We could totes have `-o` and `-O` flags for optimize and output respectively, you think? - or do you know of a better word?

**Comment by yoshuawuyts** [comment]
there's also the option of adding the `--enhance` flag... https://www.youtube.com/watch?v=Vxq9yj2pVWk

**Comment by marionebl** [comment]
Isn't the `-d/--directory` proposed in #57 the exact same thing as the new meaning of `-o/--out`? `-d` looks just fine to me, let's avoid more option renaming – API stability and documentation is more important than getting the perfect keywords in line imo.

**Comment by yoshuawuyts** [comment]
yeah sounds good

**Comment by timwis** [comment]
sold
