### ISSUE TITLE
Register everything in constructor

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/bankai#58]
Currently, you must register css before js, but register js before outputting css. What if everything is registered in the bankai constructor? it would return an assets object with registered html, js, css methods. The order of registration would thus be abstracted.

**Comment by yoshuawuyts** [comment]
yeah sounds good to me!

**Comment by timwis** [comment]
How's this feel? Usage would be like:

```js
const browserify = require('browserify')
const bankai = require('bankai')
const http = require('http')
const path = require('path')

const client = path.join(__dirname, 'client.js')

const assets = bankai({
  js: {
    browserify: browserify,
    src: client
    // other opts here, at top level (rather than inside `opts` object)
  },
  html: true,
  css: true
})

http.createServer((req, res) => {
  switch req.url {
    case '/': return assets.html(req, res).pipe(res)
    case '/bundle.js': return assets.js(req, res).pipe(res)
    case '/bundle.css': return assets.css(req, res).pipe(res)
    default: return res.statusCode = 404 && res.end('404 not found')
  }
}).listen(8080)
```
`html` and `css` could be objects as well, if you want to configure them

**Comment by yoshuawuyts** [comment]
Yeah I like the idea! - I find nested objects can be hard to remember though, so maybe we should go for a flat scope:

```js
const assets = bankai({
  browserify: browserify,
  src: client,
  html: true,
  css: true,
  js: true,
  cssEntry: '/bundle.css',
  jsEntry: '/bundle.js'
})
```
I think this is only feasible because we're not aiming to add a mad amount of of options. What do you think?

**Comment by timwis** [comment]
What about supporting the ability to pass arguments to browserify? Ie. Debug, transform, etc.

**Comment by yoshuawuyts** [comment]
Oh hey yeah, so if we're not passing in `browserify` anymore as per #62 then the `browserify` arg is open to be an object of options. That could work right?

**Comment by timwis** [comment]
Good idea. In fact, `cssEntry` and `jsEntry` are really just options of `create-html`, similar to browserify's `opts`. Playing around with it a bit, how about this?

If you're happy with the out-of-the-box config,
```javascript
const assets = bankai({
  entry: 'index.js',
  optimize: true,
  js: true,
  html: true,
  css: true
})
```

If you want to customize,
```javascript
const assets = bankai({
  entry: 'index.js',
  optimize: true,
  js: {
    debug: true
  },
  html: {
    title: 'Hello, world',
    script: 'bundle.js',
    css: 'styles.css'
  },
  css: {
    use: 'sheetify-cssnext'
  }
})
```

I was also considering using the underlying library names to make it clear to the user that they're just passing options to the underlying libraries, but I'm leaning more towards the above (html/js/css):

```javascript
const assets = bankai({
  entry: 'index.js',
  optimize: true,
  browserify: {
    debug: true
  },
  createHtml: {
    title: 'Hello, world',
    script: 'bundle.js',
    css: 'styles.css'
  },
  sheetify: {
    use: 'sheetify-cssnext'
  }
})
```

Thoughts?

**Comment by yoshuawuyts** [comment]
@timwis I like your suggestion; think it makes for a intuitive API. All :+1: for that :D

**Comment by yoshuawuyts** [comment]
Done in 4.0.0, close enough

**Comment by timwis** [comment]
Thanks! Sorry for dropping the ball on this one :/
