### ISSUE TITLE
Make browserify optional arg of bankai.js()

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/bankai#62]
Is it required in order to avoid peer dependencies or something? Seems like a rare case someone would want to pass anything other than browserify (not even sure what else you could pass).

**Comment by yoshuawuyts** [comment]
Yeah you're right - when I built this the idea was that this way people could upgrade their `browserify` version independently of `bankai` so this package would be low-maintenance and still valuable down the line. `greenkeeper` makes it easier to keep dependencies fresh making the argument moot, so I'm all for bundling in `browserify` now :+1: :sparkles:

**Comment by yoshuawuyts** [comment]
Done in 4.0.0
