### ISSUE TITLE
start doesn't work on node v4.4.5

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/bankai#66]
Just FYI, `const entry = ['.', '/'].includes(first)` throws an error on `includes` as it's an ES6 feature

**Comment by yoshuawuyts** [comment]
ohh, yeah we should at least target the latest LTS release

**Comment by marionebl** [comment]
Fixed with [v3.3.0](https://github.com/yoshuawuyts/bankai/releases/tag/v3.3.0)
