### ISSUE TITLE
[feature] serve assets

### ISSUE THREAD

**Issue by ungoldman** [yoshuawuyts/bankai#82]
Wondering what is the best approach for serving fonts with bankai. Has anyone tried doing this yet?

Experimenting with `sheetify` and `font-awesome` for now.

**Comment by timwis** [comment]
Haha wow, literally this morning I was faced with the same question. Couldn't get font awesome to work with sheetify, unless you write your own index.html.

I ended up using fontello.com, which lets you pick the icons you need and download them. Would be nice if you could pull them in via package.json or something, but it doesn't feel too bad to vendor a few icons. The result is a fonts dir in the repo, which, if you use bankai build you'll have to copy the fonts dir to the dist/built dir.

Example: https://github.com/timwis/form-designer in the package.json scripts 

Let me know if you come up with anything better.

**Comment by ungoldman** [comment]
Experimenting with passing transforms to browserify via `assets.js(browserify, src, opts?)` but I don't seem to be getting it quite right.

We succeeded in dealing with font assets in [hyperamp](https://github.com/hypermodules/hyperamp) by using this configuration:

```json
  "browserify": {
    "transform": [
      [
        "sheetify/transform",
        {
          "use": [
            [
              "sheetify-postcss",
              {
                "plugins": [
                  "postcss-copy-assets"
                ],
                "to": "./renderer/dist/bundle.css"
              }
            ]
          ]
        }
      ]
    ]
  },
```

> https://github.com/hypermodules/hyperamp/blob/master/package.json#L6-L25

(sorry [fixpack](https://www.npmjs.com/package/fixpack) expands json a little aggressively)

**Comment by ungoldman** [comment]
I think bankai's css method may not be able to support the above transform because it requires writing a CSS file to disk, and bankai's css method returns a css stream that isn't written anywhere.

**Comment by yoshuawuyts** [comment]
So to get this straight: if you can pass more stuff to `index.html` and we're good? Or what do we need? We still don't have a flow for assets yet, and feel that might be important (images, anyone?)

What kind of assets would we need this to work well?

cc/ @kriesse any thoughts on asset types / steps you commonly run when processing assets?

**Comment by yoshuawuyts** [comment]
ok gonna rename this to "handle assets" because the feature is slightly larger in scope than just fonts

**Comment by yoshuawuyts** [comment]
Hmm, yeah so what I'm thinking right now is serving all assets from a directory
over `http` and we could like pretend they're from another. E.g.

start command:
```sh
# start command; pass in an assets directory. Defaults to "assets/" if it exists
$ bankai start index.js --assets="assets/"
```

project directory structure:
```txt
index.js
assets/
  my-cool-image.jpg
```

index.js:
```js
html`<img src="assets/my-cool-image.jpg"></img>`
```

compiled directory structure:
```txt
dist/
  bundle.js
  bundle.css
  index.html
  my-cool-image.jpg
```

The whole `assets` dir is served in this example. Only a directory can be
served as to prevent weird attacks using escaping of things and the like.

What I'm wondering actually is if we should apply magic to make the `assets/`
prefix unnecessary for the `html` file or if that adds weird gotchas.
Thoughts very much welcome!

A step we could take after this is run optimizations for several well-known
file types like images and the like. I'm not sure if that'd be an optimization
or maybs another package even but yeah it's possible at least (:

Let me know what y'all think - thoughts very welcome! :sparkles:

**Comment by yoshuawuyts** [comment]
note that this does not address `svg` sprites - I feel that might be a separate concern that's worth exploring in a different issue

**Comment by ungoldman** [comment]
Hi @yoshuawuyts, sorry it's taken me so long to get back to you! Busy month 😅 

The above sounds like a very reasonable approach to me.

In regards to magic, my first thought was that mirroring the naming structure of the target directory is probably a good way to go. So for example if I have a folder like this:

```
index.js
static/
  img/
    dog.jpg
  fonts/
    comic-sans.ttf
```

and I do

```
bankai start index.js --assets="static/"
```

I would maybe expect to be able to access things as `<img src="/img/dog.jpg" />`.

However upon further consideration, this expectation is probably a holdover from working with older frameworks like express/rails/etc -- maybe avoiding magic and keeping things scoped to `/assets/` would make sense. Either way works for me.

Thanks!

**Comment by yoshuawuyts** [comment]
Haha no worries - thanks for the feedback! Yeah think I prefer keeping as
little magic as possible; wooh! :D

**Comment by yoshuawuyts** [comment]
I wonder tho - is `brfs` perhaps enough for this in most cases? - I tried implementing this but it became real hairy real fast :/

**Comment by YerkoPalma** [comment]
Does the assets option resolve this? or is this still an issue??

**Comment by yoshuawuyts** [comment]
assets can be serveddd nowwwww :tada:

**Comment by goto-bus-stop** [comment]
Files in `assets/`, `content/` and `public/` folders are served on their respective endpoints. If you want to add remote files like bootstrap you can use a [custom index.html](https://github.com/choojs/bankai/#custom-html) file.

```html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
</head>
<body>
</body>
</html>
```
